### ISSUE TITLE
CSS support

### ISSUE THREAD

**Issue by fregante** [licg9999/transpile-webpack-plugin#44]
I have this in my entry file:

```js
import './refined-github.css';
```

This normally generates `entry.js` and `refined-github.css` using `mini-css-extract-plugin`

When adding your plugin, the output is:

### entry.js

This file should be empty, but instead  it tries to import the CSS file:
```js
(() => {
  "use strict";
  var __webpack_require__ = {
    r: exports => {
      if ("undefined" != typeof Symbol && Symbol.toStringTag) Object.defineProperty(exports, Symbol.toStringTag, {
        value: "Module"
      });
      Object.defineProperty(exports, "__esModule", {
        value: !0
      });
    }
  }, __webpack_exports__ = {};
  __webpack_require__.r(__webpack_exports__);
  require("./refined-github.css");
  module.exports = __webpack_exports__;
})();
```

### refined-github.css

This is a .css file with JS inside, that does nothing

```js
(() => {
  "use strict";
  var __webpack_require__ = {
    r: exports => {
      if ("undefined" != typeof Symbol && Symbol.toStringTag) Object.defineProperty(exports, Symbol.toStringTag, {
        value: "Module"
      });
      Object.defineProperty(exports, "__esModule", {
        value: !0
      });
    }
  }, __webpack_exports__ = {};
  __webpack_require__.r(__webpack_exports__);
  module.exports = __webpack_exports__;
})();
```

### refined-github.css.css

This contains the CSS from the original CSS file

# Config

My config is approximately:

```js
const path = require('node:path');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const TranspilePlugin = require('transpile-webpack-plugin');

module.exports = {
	entry: 'entry.js'
	context: path.resolve('source'),
	output: {
		path: path.resolve('distribution/assets'),
	},
	module: {
		rules: [
			{
				test: /\.css$/,
				use: [
					MiniCssExtractPlugin.loader,
					'css-loader',
				],
			},
		],
	},
	plugins: [
		new MiniCssExtractPlugin(),
		new TranspilePlugin(),
	],
};
```

Full source at https://github.com/refined-github/refined-github/blob/5247e6e1887407fde5aa02e60850e71a9106c5e7/webpack.config.ts

**Comment by licg9999** [comment]
Hi @fregante, I'm glad to know the problem. Thank you.

Before I actually dive into solving the problem, would you help clarify a bit about what were you going to achieve by combining `mini-css-extract-plugin` with `transpile-webpack-plugin`?

As `mini-css-extract-plugin` heavily reorganizes CSS file emission, it currently interferes with `transpile-webpack-plugin`.

My first-instinct suggestion could be, you might try `style-loader` to take the place of `MiniCssExtractPlugin.loader` in this case. But I'd like to make any improvements in `transpile-webpack-plugin` to meet good use cases.

Please let me know your thoughts.

**Comment by fregante** [comment]
That makes sense, the expectation would be that the CSS file is extracted and *not* imported via webpack. I think that if I remove the other plugin, the CSS file will be extracted, but the output.js file will still try to load it. 

I'll try it later

**Comment by licg9999** [comment]
Oh, I see your concerns.

I assume setting the option [`runtime` of `mini-css-extract-plugin`](https://github.com/webpack-contrib/mini-css-extract-plugin#runtime) as `false` might help with that.

Also, just let me know if it doesn't help.

**Comment by fregante** [comment]
## Without `mini-css-extract-plugin`

### refined-github.css
```css
(() => {
  "use strict";
  var __webpack_modules__ = {
    23964: (module, __webpack_exports__, __webpack_require__) => {
      __webpack_require__.r(__webpack_exports__);
      __webpack_require__.d(__webpack_exports__, {
        default: () => __WEBPACK_DEFAULT_EXPORT__
      });
      var _node_modules_css_loader_dist_runtime_noSourceMaps_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(38602), _node_modules_css_loader_dist_runtime_noSourceMaps_js__WEBPACK_IMPORTED_MODULE_0___default = __webpack_require__.n(_node_modules_css_loader_dist_runtime_noSourceMaps_js__WEBPACK_IMPORTED_MODULE_0__), _node_modules_css_loader_dist_runtime_api_js__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(11529), ___CSS_LOADER_EXPORT___ = __webpack_require__.n(_node_modules_css_loader_dist_runtime_api_js__WEBPACK_IMPORTED_MODULE_1__)()(_node_modules_css_loader_dist_runtime_noSourceMaps_js__WEBPACK_IMPORTED_MODULE_0___default());
      ___CSS_LOADER_EXPORT___.push([ module.id, ":root {\n\t--rgh-green: var(--color-success-fg, #1a7f37);\n\t--rgh-red: var(--color-danger-fg, #cf222e);

etc
```

### With `new MiniCssExtractPlugin({runtime: false})`

Same as the original report: 

- `refined-github.css` with JS that does nothing
- `refined-github.css.css` with the correct CSS

In reality this is almost good. However now I realize that this plugin can't work for me because it uses Node’s own `require` instead of `import`. I won't run this code in Node, so it wouldn't help me anyway.

I'm closing for now
